/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alien.glb -t -o components/arena/alien.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.SkinnedMesh
    Mesh_1: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Ch44_Body: THREE.MeshStandardMaterial
    Ch44_body1: THREE.MeshStandardMaterial
  }
}

type AlienProps = JSX.IntrinsicElements['group'] & { 
  text?: string
  animType?: 'twerk' | 'drunk'
}

export function Alien({ text = "We see you...", animType = 'twerk', ...props }: AlienProps) {
  const group = React.useRef<THREE.Group>(null)
  
  // Load the base GLTF model (which contains 'mixamo.com' - twerk)
  const { scene, animations: twerkAnimations } = useGLTF('/alien.glb')
  
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  
  const allAnimations = React.useMemo(() => {
    const twerk = twerkAnimations[0]
    if (twerk) twerk.name = 'twerk'
    return [twerk].filter(Boolean) as THREE.AnimationClip[]
  }, [twerkAnimations])

  const { actions } = useAnimations(allAnimations, group)

  React.useEffect(() => {
    if (actions) {
      // Stop all first
      Object.values(actions).forEach(action => action?.stop())
      // Play selected
      if (actions[animType]) {
        actions[animType].reset().play()
      }
    }
  }, [actions, animType])

  return (
    <group ref={group} {...props} dispose={null}>
      <pointLight position={[0, 2, 0]} distance={8} intensity={2} color="#00ff44" />
      <Html position={[0, 2.5, 0]} center distanceFactor={15}>
        <div className="bg-black/80 text-green-400 px-3 py-1 rounded border border-green-500/50 whitespace-nowrap font-mono text-sm shadow-[0_0_10px_rgba(34,197,94,0.5)]">
          {text}
        </div>
      </Html>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Ch44">
            <skinnedMesh name="Mesh" castShadow receiveShadow geometry={nodes.Mesh.geometry} material={materials.Ch44_Body} skeleton={nodes.Mesh.skeleton} />
            <skinnedMesh name="Mesh_1" castShadow receiveShadow geometry={nodes.Mesh_1.geometry} material={materials.Ch44_body1} skeleton={nodes.Mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alien.glb')
