/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/skeleton-warrior.glb -t -o components/arena/skeleton-warrior.tsx 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type ActionName = 'Attack' | 'Death' | 'Idle' | 'Walk'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Sphere_1: THREE.Mesh
    Sphere_2: THREE.Mesh
  }
  materials: {
    Bone: THREE.MeshStandardMaterial
    GlowEye: THREE.MeshStandardMaterial
    DarkMetal: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type SkeletonWarriorProps = JSX.IntrinsicElements['group']

export function SkeletonWarrior(props: SkeletonWarriorProps) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations: origAnimations } = useGLTF('/skeleton-warrior.glb') as GLTFResult
  
  const fbx = useFBX('/Ch44_nonPBR@Drunk Walk.fbx')
  
  const allAnimations = React.useMemo(() => {
    const arr = [...origAnimations]
    if (fbx.animations.length > 0) {
      const drunk = fbx.animations[0].clone()
      drunk.name = 'Walk'
      
      // Attempt to remap Mixamo bone names to the skeleton rig names
      drunk.tracks.forEach(track => {
        let newName = track.name
        newName = newName.replace('mixamorig', '')
        
        // Basic mapping for limbs (e.g. LeftShoulder -> ShoulderL)
        newName = newName.replace('LeftShoulder', 'ShoulderL')
        newName = newName.replace('LeftArm', 'UpperArmL')
        newName = newName.replace('LeftForeArm', 'LowerArmL')
        newName = newName.replace('LeftHand', 'HandL')
        newName = newName.replace('LeftUpLeg', 'UpperLegL')
        newName = newName.replace('LeftLeg', 'LowerLegL')
        newName = newName.replace('LeftFoot', 'FootL')
        
        newName = newName.replace('RightShoulder', 'ShoulderR')
        newName = newName.replace('RightArm', 'UpperArmR')
        newName = newName.replace('RightForeArm', 'LowerArmR')
        newName = newName.replace('RightHand', 'HandR')
        newName = newName.replace('RightUpLeg', 'UpperLegR')
        newName = newName.replace('RightLeg', 'LowerLegR')
        newName = newName.replace('RightFoot', 'FootR')
        
        track.name = newName
      })
      
      const walkIndex = arr.findIndex(a => a.name === 'Walk')
      if (walkIndex >= 0) {
        arr[walkIndex] = drunk as GLTFAction
      } else {
        arr.push(drunk as GLTFAction)
      }
    }
    return arr
  }, [origAnimations, fbx])

  const { actions } = useAnimations(allAnimations, group)
  
  const [currentAnim, setCurrentAnim] = useState<string | null>(null)

  // Turn on emissive glow for the eyes
  useEffect(() => {
    materials.GlowEye.emissive = new THREE.Color('#ff2200')
    materials.GlowEye.emissiveIntensity = 2
  }, [materials])

  useEffect(() => {
    if (actions && actions['Idle']) {
      actions['Idle'].reset().fadeIn(0.5).play()
      setCurrentAnim('Idle')
    }
  }, [actions])

  const prevPos = useRef(new THREE.Vector3())

  useFrame((state, delta) => {
    if (!group.current || !actions) return
    const camera = state.camera

    const forward = new THREE.Vector3(0, 0, -1).applyQuaternion(camera.quaternion)
    forward.y = 0
    if (forward.lengthSq() > 0.001) forward.normalize()

    const targetPos = camera.position.clone().add(forward.clone().multiplyScalar(5))
    targetPos.y = -2

    group.current.position.lerp(targetPos, 15 * delta)

    const angle = Math.atan2(forward.x, forward.z)
    group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, angle, 12 * delta)

    const dist = camera.position.distanceTo(prevPos.current)
    const isMoving = dist > 0.09

    if (isMoving) {
      if (currentAnim !== 'Walk' && actions['Walk']) {
        if (currentAnim && actions[currentAnim]) actions[currentAnim].fadeOut(0.2)
        actions['Walk'].reset().fadeIn(0.2).play()
        setCurrentAnim('Walk')
      }
    } else {
      if (currentAnim !== 'Idle' && actions['Idle']) {
        if (currentAnim && actions[currentAnim]) actions[currentAnim].fadeOut(0.2)
        actions['Idle'].reset().fadeIn(0.2).play()
        setCurrentAnim('Idle')
      }
    }

    prevPos.current.copy(camera.position)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SkeletonRig">
          <group name="Root">
            <group name="Hips" position={[0, 0.88, 0]}>
              <group name="Spine" position={[0, 0.07, 0]}>
                <group name="Chest" position={[0, 0.2, 0]}>
                  <group name="Neck" position={[0, 0.25, 0]}>
                    <group name="Head" position={[0, 0.1, 0]} />
                  </group>
                  <group name="ShoulderL" position={[-0.15, 0.27, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                    <group name="UpperArmL" position={[0, 0.07, 0]} rotation={[-0.945, 0.945, 0]}>
                      <group name="LowerArmL" position={[0, 0.222, 0]} rotation={[-0.1, 0.336, -0.276]}>
                        <group name="HandL" position={[0, 0.168, 0]} rotation={[0, 0.303, -0.303]} />
                      </group>
                    </group>
                  </group>
                  <group name="ShoulderR" position={[0.15, 0.27, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                    <group name="UpperArmR" position={[0, 0.07, 0]} rotation={[-0.945, -0.945, 0]}>
                      <group name="LowerArmR" position={[0, 0.222, 0]} rotation={[0, -0.625, 0.625]}>
                        <group name="HandR" position={[0, 0.19, 0]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="UpperLegL" position={[-0.1, -0.03, 0]} rotation={[-3.138, -0.057, 0.057]}>
                <group name="LowerLegL" position={[0, 0.351, 0]} rotation={[0, 0.057, -0.057]}>
                  <group name="FootL" position={[0, 0.42, 0]} rotation={[Math.PI / 4, 0, 0]} />
                </group>
              </group>
              <group name="UpperLegR" position={[0.1, -0.03, 0]} rotation={[-3.138, 0.057, -0.057]}>
                <group name="LowerLegR" position={[0, 0.351, 0]} rotation={[0, -0.057, 0.057]}>
                  <group name="FootR" position={[0, 0.42, 0]} rotation={[Math.PI / 4, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
          <group name="SkeletonWarrior">
            <mesh name="Sphere" castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials.Bone} />
            <mesh name="Sphere_1" castShadow receiveShadow geometry={nodes.Sphere_1.geometry} material={materials.GlowEye} />
            <mesh name="Sphere_2" castShadow receiveShadow geometry={nodes.Sphere_2.geometry} material={materials.DarkMetal} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/skeleton-warrior.glb')
